spring:
  application:
    name: SimpleWeb

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

#  datasource:
#    url: jdbc:mysql://localhost:3306/testdb
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password:
